AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template for a PDF processing function.

Resources:
  PdfGenerator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 3
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /pdf-generator
            Method: POST
            Auth:
              ApiKeyRequired: true
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:HeadObject
            Resource: arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-kdvjqzoec6pg/*  # Make sure to replace with your actual bucket name

  # Usage Plan with Dependency on API Stage
  PdfGeneratorUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ServerlessRestApiProdStage  # Ensure API Gateway Stage is created first
    Properties:
      ApiStages:
        - ApiId: !Ref ServerlessRestApi  # The API Gateway ID created by SAM
          Stage: Prod  # Reference the correct stage
      UsagePlanName: PdfGeneratorUsagePlan
      Description: Usage plan for the PDF function
      Throttle:
        RateLimit: 10
        BurstLimit: 2

  # API Key with Dependency on API Stage
  PdfGeneratorApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: ServerlessRestApiProdStage  # Ensure API Gateway Stage is created first
    Properties:
      Enabled: true
      Name: PdfGeneratorApiKey
      StageKeys:
        - RestApiId: !Ref ServerlessRestApi  # The API Gateway ID created by SAM
          StageName: Prod  # Reference the correct stage

  PdfGeneratorUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref PdfGeneratorApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref PdfGeneratorUsagePlan

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
